
development:
  adapter: postgresql
  encoding: unicode
  database: deadmusic_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: deadmusic_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: deadmusic_production
  pool: 5

